package com.EventBrite.service;

import com.EventBrite.model.Event;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.*;

@Service
public class AIService {

    @Value("${deepseek.api.key}")
    private String apiKey;

    private static final String DEEPSEEK_API_URL = "https://api.deepseek.com/v1/chat/completions";
    private static final String DEEPSEEK_MODEL = "deepseek-chat"; // Correct model name

    // Add a proper Message class instead of using Map
    private static class Message {
        private String role;
        private String content;

        public Message(String role, String content) {
            this.role = role;
            this.content = content;
        }

        // Getters
        public String getRole() { return role; }
        public String getContent() { return content; }
    }

    public Event generateEvent(Event eventDetails) {
        try {
            RestTemplate restTemplate = new RestTemplate();
            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            headers.setBearerAuth(apiKey);

            // Construct message using proper object
            Message message = new Message("user", String.format(
                    "Generate a short, creative event title and description for the following details:\n" +
                            "Date: %s\nTime: %s - %s\nLocation: %s",
                    eventDetails.getDate(),
                    eventDetails.getStartTime(),
                    eventDetails.getEndTime(),
                    eventDetails.getLocation()
            ));

            // Create request body
            Map<String, Object> requestBody = new HashMap<>();
            requestBody.put("model", DEEPSEEK_MODEL); // Use DeepSeek model
            requestBody.put("messages", Collections.singletonList(message));
            requestBody.put("temperature", 0.7);

            HttpEntity<Map<String, Object>> request = new HttpEntity<>(requestBody, headers);
            ResponseEntity<String> response = restTemplate.postForEntity(DEEPSEEK_API_URL, request, String.class);

            if (response.getStatusCode().is2xxSuccessful()) {
                ObjectMapper mapper = new ObjectMapper();
                JsonNode json = mapper.readTree(response.getBody());

                String responseText = json.path("choices")
                        .get(0)
                        .path("message")
                        .path("content")
                        .asText();

                // Improved parsing logic
                String[] parts = responseText.split("\n");
                String title = parts.length > 0 ?
                        parts[0].replaceAll("(?i)^Title:?", "").trim() :
                        "AI Event";

                String description = parts.length > 1 ?
                        String.join("\n", Arrays.copyOfRange(parts, 1, parts.length))
                                .replaceAll("(?i)^Description:?", "").trim() :
                        "Generated by AI.";

                return new Event(
                        title,
                        eventDetails.getDate(),
                        eventDetails.getStartTime(),
                        eventDetails.getEndTime(),
                        eventDetails.getLocation(),
                        description
                );
            } else {
                System.err.println("DeepSeek API Error: " + response.getStatusCode() + " - " + response.getBody());
            }

        } catch (Exception e) {
            System.err.println("API Request Failed: " + e.getMessage());
            e.printStackTrace();
        }

        return createFallbackEvent(eventDetails);
    }

    private Event createFallbackEvent(Event original) {
        return new Event(
                original.getTitle(),
                original.getDate(),
                original.getStartTime(),
                original.getEndTime(),
                original.getLocation(),
                "AI could not generate event details."
        );
    }
}